FEEDS = [
    {"name":"9 News", "url": "https://www.9news.com/feeds/syndication/rss/news"},
    {"name":"New York Times", "url": "https://content.api.nytimes.com/svc/news/v3/all/recent.rss"},
    {"name":"Independent", "url": "https://www.independent.co.uk/news/rss"},
    {"name":"The Guardian", "url": "https://www.theguardian.com/world/rss"},
    {"name":"Sbs", "url":"https://www.sbs.com.au/news/topic/latest/feed"},
    {"name":"Fox News", "url":"https://moxie.foxnews.com/google-publisher/world.xml"},
    {"name":"Wall Street", "url":"https://feeds.a.dj.com/rss/RSSWorldNews.xml"},
    {"name":"Forbes (Innovation)", "url":"https://www.forbes.com/innovation/feed"},
    {"name":"Forbes (Business)", "url":"https://www.forbes.com/business/feed"},
    {"name":"BBC", "url":"http://feeds.bbci.co.uk/news/world/rss.xml"},
    {"name":"News.com", "url":"https://www.news.com.au/content-feeds/latest-news-world/"},
    {"name":"SMH", "url":"https://www.smh.com.au/rss/feed.xml"},
    {"name":"Herald Sun", "url":"https://www.heraldsun.com.au/rss"},
    {"name":"ABC", "url":"https://www.abc.net.au/news/feed/51120/rss.xml"},
    {"name":"The Sun Daily", "url":"https://www.thesundaily.my/rss/world"},
    {"name":"Washington Post", "url":"https://feeds.washingtonpost.com/rss/politics"},
    {"name":"CNN", "url":"http://rss.cnn.com/rss/edition.rss"},
    #{"name":"Investopedia", "url":"https://www.investopedia.com/feedbuilder/feed/getfeed?feedName=rss_articles"},
    {"name":"Reuters", "url":"https://www.reutersagency.com/feed/?taxonomy=best-sectors&post_type=best"},
    {"name":"Yahoo Finance", "url":"https://www.yahoo.com/news/rss"},
    {"name":"The Hill", "url":"https://thehill.com/news/feed/"},
    {"name":"The Economist", "url":"https://www.economist.com/the-world-this-week/rss.xml"},
    {"name":"The Atlantic", "url":"https://www.theatlantic.com/feed/all/"},
    {"name":"News Week", "url":"http://www.newsweek.com/rss"},
    {"name":"The Verge", "url":"https://www.theverge.com/rss/index.xml"},
    {"name":"Tech Crunch", "url":"https://techcrunch.com/feed/"},
    {"name":"Business Insider", "url":"http://feeds2.feedburner.com/businessinsider"},
    {"name":"China Daily", "url":"http://www.chinadaily.com.cn/rss/world_rss.xml"},
    #{"name":"The Hindu", "url":"https://www.thehindu.com/news/feeder/default.rss"},
    {"name":"Global Times", "url":"http://www.globaltimes.cn/rss/outbrain.xml"},
    {"name":"CoinDesk", "url":"https://feeds.feedburner.com/CoinDesk"},
    {"name":"Fortune", "url":"http://fortune.com/feed/"},
    {"name":"Reddit News", "url":"https://www.reddit.com/r/news/.rss"},
    {"name":"Reddit World News", "url":"https://www.reddit.com/r/worldnews/.rss"},
    {"name":"CBC", "url": "https://www.cbc.ca/cmlink/rss-topstories"},
    {"name":"CTVnews", "url": "https://www.ctvnews.ca/rss/ctvnews-ca-top-stories-public-rss-1.822009"},
    {"name":"France24", "url": "https://www.france24.com/en/rss"},
    {"name":"RT", "url": "https://www.rt.com/rss/"},
    {"name":"DW", "url": "https://rss.dw.com/rdf/rss-en-all"},
    {"name":"Global News", "url": "https://globalnews.ca/feed/"}
]
